Import Necessary Libraries

In [109]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

Importing Dataset

In [8]:
df = pd.read_csv(r'C:\Users\amitd\Downloads\titanic\train.csv')

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Data Cleaning

In [12]:
df.drop(["Cabin", "Embarked"], axis=1, inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

In [14]:
df["Age"].fillna(df["Age"].median(), inplace = True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

Data Preprocessing

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500

In [18]:
df['Sex'] = le.fit_transform(df['Sex'])
df['Name'] = le.fit_transform(df['Name'])
df['Ticket'] = le.fit_transform(df['Ticket'])

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,108,1,22.0,1,0,523,7.2500
1,2,1,1,190,0,38.0,1,0,596,71.2833
2,3,1,3,353,0,26.0,0,0,669,7.9250
3,4,1,1,272,0,35.0,1,0,49,53.1000
4,5,0,3,15,1,35.0,0,0,472,8.0500

In [20]:
x = df.drop("Survived", axis=1)
y = df["Survived"]

Logistic Regression

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [23]:
y_pred = model.predict(X_test)

In [24]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0])

In [25]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
accuracy_score(y_test, y_pred)

0.776536312849162

In [28]:
confusion_matrix(y_test, y_pred)

array([[89, 16],
       [24, 50]])

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82       105
           1       0.76      0.68      0.71        74

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.77       179
weighted avg       0.78      0.78      0.77       179

KNN

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [31]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
model_Knn = KNeighborsClassifier(n_neighbors= 5)
model_Knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [34]:
y_pred_knn = model_Knn.predict(X_test_scaled)

In [35]:
accuracy_score(y_test, y_pred_knn)

0.7988826815642458

In [36]:
confusion_matrix(y_test, y_pred_knn)

array([[91, 14],
       [22, 52]])

In [37]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.81      0.87      0.83       105
           1       0.79      0.70      0.74        74

    accuracy                           0.80       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.80      0.80      0.80       179

Naive Bayes

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model_NB = GaussianNB()
model_NB.fit(X_train, y_train)

GaussianNB()

In [40]:
y_pred_NB = model_NB.predict(X_test)
y_pred_NB

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [41]:
accuracy_score(y_test, y_pred_NB)

0.7653631284916201

In [42]:
confusion_matrix(y_test, y_pred_NB)

array([[82, 23],
       [19, 55]])

In [43]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.81      0.78      0.80       105
           1       0.71      0.74      0.72        74

    accuracy                           0.77       179
   macro avg       0.76      0.76      0.76       179
weighted avg       0.77      0.77      0.77       179

Decision Tree

In [44]:
from sklearn.tree import DecisionTreeClassifier

In [45]:
model_DT = DecisionTreeClassifier(random_state=42)

In [46]:
model_DT.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [47]:
y_pred_DT = model_DT.predict(X_test_scaled)
y_pred_DT

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1])

In [48]:
accuracy_score(y_test, y_pred_DT)

0.7039106145251397

In [49]:
confusion_matrix(y_test, y_pred_DT)

array([[79, 26],
       [27, 47]])

In [50]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75       105
           1       0.64      0.64      0.64        74

    accuracy                           0.70       179
   macro avg       0.69      0.69      0.69       179
weighted avg       0.70      0.70      0.70       179

Support Vector Machines

In [51]:
from sklearn.svm import SVC

In [52]:
model_SVM = SVC(kernel='rbf')
model_SVM.fit(X_train_scaled, y_train)

SVC()

In [53]:
y_pred_SVM = model_SVM.predict(X_test_scaled)
y_pred_SVM

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0])

In [54]:
accuracy_score(y_test, y_pred_SVM)

0.8100558659217877

In [55]:
confusion_matrix(y_test, y_pred_SVM)

array([[92, 13],
       [21, 53]])

In [56]:
print(classification_report(y_test, y_pred_SVM))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       105
           1       0.80      0.72      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

Cross Validation

In [57]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

In [58]:
from sklearn.model_selection import cross_val_score

In [59]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [60]:
scores = cross_val_score(model_SVM, X_scaled, y, cv=5)
print("Cross-validation scores:", scores)

Cross-validation scores: [0.84357542 0.82022472 0.80898876 0.80898876 0.83707865]

In [61]:
print("Average cross-validation score:", np.mean(scores))

Average cross-validation score: 0.8237712635741637

Grid Search CV

In [62]:
df1 = sns.load_dataset('iris')
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [63]:
df1['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [65]:
x = df1.drop("species", axis=1)
y = df1["species"]

In [66]:
from sklearn.neighbors import KNeighborsClassifier
model_Knn = KNeighborsClassifier(n_neighbors= 5)
model_Knn.fit(X_train, y_train)

KNeighborsClassifier()

In [67]:
model_Knn.score(X_test, y_test)

0.664804469273743

In [68]:
from sklearn.svm import SVC
model_Svm = SVC(gamma="auto")
model_Svm.fit(X_train, y_train)

SVC(gamma='auto')

In [69]:
model_Svm.score(X_test, y_test)

0.5865921787709497

In [70]:
from sklearn.model_selection import GridSearchCV
classifier = GridSearchCV((model_Svm),{
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf']
}, cv = 5, return_train_score=False)

In [71]:
classifier.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']})

In [72]:
classifier.cv_results_

{'mean_fit_time': array([1.35449054e+01, 1.36981010e-02, 3.93827374e+01, 1.69411182e-02,
        7.44920278e+01, 1.60117626e-02, 1.08647212e+02, 1.47662640e-02]),
 'std_fit_time': array([4.13450735e+00, 3.36953698e-04, 1.17922972e+01, 9.48768244e-04,
        2.76966773e+01, 2.07198579e-03, 2.12613824e+01, 4.07055033e-04]),
 'mean_score_time': array([0.00239148, 0.00778961, 0.00254622, 0.01323533, 0.00253811,
        0.01143222, 0.00357666, 0.00791755]),
 'std_score_time': array([0.00013886, 0.00021382, 0.00040655, 0.00222921, 0.00032441,
        0.00377946, 0.00114474, 0.00034637]),
 'param_C': masked_array(data=[0.1, 0.1, 1.0, 1.0, 10.0, 10.0, 100.0, 100.0],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 0.1, 'kernel': 'linear'},
  {'C': 0.1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 100, 'kernel': 'linear'},
  {'C': 100, 'kernel': 'rbf'}],
 'split0_test_score': array([0.7972028 , 0.62237762, 0.79020979, 0.62237762, 0.82517483,
        0.62237762, 0.81818182, 0.62237762]),
 'split1_test_score': array([0.8041958 , 0.62237762, 0.81118881, 0.62237762, 0.8041958 ,
        0.62237762, 0.8041958 , 0.62237762]),
 'split2_test_score': array([0.75352113, 0.62676056, 0.77464789, 0.62676056, 0.81690141,
        0.62676056, 0.79577465, 0.62676056]),
 'split3_test_score': array([0.76056338, 0.62676056, 0.76056338, 0.62676056, 0.74647887,
        0.62676056, 0.71830986, 0.62676056]),
 'split4_test_score': array([0.82394366, 0.61971831, 0.83098592, 0.61971831, 0.78873239,
        0.61971831, 0.80985915, 0.61971831]),
 'mean_test_score': array([0.78788535, 0.62359894, 0.79351916, 0.62359894, 0.79629666,
        0.62359894, 0.78926426, 0.62359894]),
 'std_test_score': array([0.02675981, 0.00275805, 0.02517592, 0.00275805, 0.02778464,
        0.00275805, 0.0362222 , 0.00275805]),
 'rank_test_score': array([4, 5, 2, 5, 1, 5, 3, 5], dtype=int32)}

In [73]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,13.544905,4.134507,0.002391,0.000139,0.1,linear,"{'C': 0.1, 'kernel': 'linear'}",0.797203,0.804196,0.753521,0.760563,0.823944,0.787885,0.026760,4
1,0.013698,0.000337,0.007790,0.000214,0.1,rbf,"{'C': 0.1, 'kernel': 'rbf'}",0.622378,0.622378,0.626761,0.626761,0.619718,0.623599,0.002758,5
2,39.382737,11.792297,0.002546,0.000407,1.0,linear,"{'C': 1, 'kernel': 'linear'}",0.790210,0.811189,0.774648,0.760563,0.830986,0.793519,0.025176,2
3,0.016941,0.000949,0.013235,0.002229,1.0,rbf,"{'C': 1, 'kernel': 'rbf'}",0.622378,0.622378,0.626761,0.626761,0.619718,0.623599,0.002758,5
4,74.492028,27.696677,0.002538,0.000324,10.0,linear,"{'C': 10, 'kernel': 'linear'}",0.825175,0.804196,0.816901,0.746479,0.788732,0.796297,0.027785,1
5,0.016012,0.002072,0.011432,0.003779,10.0,rbf,"{'C': 10, 'kernel': 'rbf'}",0.622378,0.622378,0.626761,0.626761,0.619718,0.623599,0.002758,5
6,108.647212,21.261382,0.003577,0.001145,100.0,linear,"{'C': 100, 'kernel': 'linear'}",0.818182,0.804196,0.795775,0.718310,0.809859,0.789264,0.036222,3
7,0.014766,0.000407,0.007918,0.000346,100.0,rbf,"{'C': 100, 'kernel': 'rbf'}",0.622378,0.622378,0.626761,0.626761,0.619718,0.623599,0.002758,5

In [74]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0      0.1       linear         0.787885
1      0.1          rbf         0.623599
2      1.0       linear         0.793519
3      1.0          rbf         0.623599
4     10.0       linear         0.796297
5     10.0          rbf         0.623599
6    100.0       linear         0.789264
7    100.0          rbf         0.623599

In [75]:
from sklearn.model_selection import RandomizedSearchCV
classifier_r = RandomizedSearchCV((model_Svm),{
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf']
}, n_iter = 4, cv = 5, return_train_score=False)

In [76]:
classifier_r.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'kernel': ['linear', 'rbf']})

In [77]:
results_r = pd.DataFrame(classifier_r.cv_results_)
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.039332,0.009852,0.018677,0.001695,rbf,10.0,"{'kernel': 'rbf', 'C': 10}",0.622378,0.622378,0.626761,0.626761,0.619718,0.623599,0.002758,3
1,0.024643,0.007260,0.014742,0.005111,rbf,100.0,"{'kernel': 'rbf', 'C': 100}",0.622378,0.622378,0.626761,0.626761,0.619718,0.623599,0.002758,3
2,16.823859,4.915194,0.002344,0.000158,linear,0.1,"{'kernel': 'linear', 'C': 0.1}",0.797203,0.804196,0.753521,0.760563,0.823944,0.787885,0.026760,2
3,116.248401,23.137429,0.003439,0.001049,linear,100.0,"{'kernel': 'linear', 'C': 100}",0.818182,0.804196,0.795775,0.718310,0.809859,0.789264,0.036222,1

In [78]:
results_r[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0     10.0          rbf         0.623599
1    100.0          rbf         0.623599
2      0.1       linear         0.787885
3    100.0       linear         0.789264

Stacking

In [79]:
from sklearn.ensemble import StackingClassifier

In [80]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,108,1,22.0,1,0,523,7.2500
1,2,1,1,190,0,38.0,1,0,596,71.2833
2,3,1,3,353,0,26.0,0,0,669,7.9250
3,4,1,1,272,0,35.0,1,0,49,53.1000
4,5,0,3,15,1,35.0,0,0,472,8.0500

In [81]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc', SVC(probability=True, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

In [82]:
meta_learner = LogisticRegression(max_iter=1000)

In [83]:
stacking_clf = StackingClassifier(estimators=base_learners, final_estimator=meta_learner, cv=5)

In [84]:
stacking_clf.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [85]:
y_pred_stack = stacking_clf.predict(X_test)

In [86]:
accuracy_score(y_test, y_pred_stack)

0.8212290502793296

Bagging with Random Forest

In [93]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
model_rf = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

In [89]:
model_rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [90]:
y_pred_rf = model_rf.predict(X_test)

In [91]:
accuracy_score(y_test, y_pred_rf)

0.8324022346368715

Boosting (AdaBoost, GradientBoost, XGBoost)

In [110]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

In [97]:
model_ada = AdaBoostClassifier(n_estimators=100, random_state=42)
model_ada.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [98]:
y_pred_ada = model_ada.predict(X_test)

In [99]:
accuracy_score(y_test, y_pred_ada)

0.8212290502793296

In [100]:
model_gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

In [101]:
model_gb.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [102]:
y_pred_gb = model_gb.predict(X_test)

In [103]:
accuracy_score(y_test, y_pred_gb)

0.7932960893854749

In [112]:
model_xgb = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42, use_label_encoder=False, eval_metric='mlogloss')

In [113]:
model_xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [114]:
y_pred_xgb = model_xgb.predict(X_test)

In [115]:
accuracy_score(y_test, y_pred_xgb)

0.8324022346368715